version: '3.8'

services:
  php:
    build:
      args:
        PHP_MODE: development

  httpd:
    ports:
      - 80:80

  mysql:
    ports:
      - 3306:3306

  minio:
    ports:
      - 9000:9000

  mailhog:
    ports:
      - 8025:8025